service: app-api

frameworkVersion: "2"

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
  - serverless-plugin-scripts
  - serverless-offline
  - serverless-associate-waf
  - serverless-stack-termination-protection
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  iamPath: ${ssm:/configuration/${self:custom.stage}/iam/path~true, ssm:/configuration/default/iam/path~true, "/"}
  iamPermissionsBoundaryPolicy: ${ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy~true, ssm:/configuration/default/iam/permissionsBoundaryPolicy~true, ""}
  serverlessTerminationProtection:
    stages: # This is a list of common names for important envs that should not be destroyed.  You can remove the stage names your project doesn't use; this list is meant to be inclusive.
      - master
      - val
      - production
      - develop
      - main
      - impl
      - val
      - prod
  infrastructureType: ${ssm:/configuration/${self:custom.stage}/infrastucture/type~true, ssm:/configuration/default/infrastucture/type~true, "development"}
  AgeRangesTableName: ${env:AGE_RANGES_TABLE_NAME, cf:database-${self:custom.stage}.AgeRangesTableName}
  AgeRangesTableArn: ${env:AGE_RANGES_TABLE_ARN, cf:database-${self:custom.stage}.AgeRangesTableArn}
  AgeRangesTableStreamArn: ${cf:database-${self:custom.stage}.AgeRangesTableStreamArn, cf:database-master.AgeRangesTableStreamArn}
  FormAnswersTableName: ${env:FORM_ANSWERS_TABLE_NAME, cf:database-${self:custom.stage}.FormAnswersTableName}
  FormAnswersTableArn: ${env:FORM_ANSWERS_TABLE_ARN, cf:database-${self:custom.stage}.FormAnswersTableArn}
  FormAnswersTableStreamArn: ${cf:database-${self:custom.stage}.FormAnswersTableStreamArn, cf:database-master.FormAnswersTableStreamArn}
  FormQuestionsTableName: ${env:FORM_QUESTIONS_TABLE_NAME, cf:database-${self:custom.stage}.FormQuestionsTableName}
  FormQuestionsTableArn: ${env:FORM_QUESTIONS_TABLE_ARN, cf:database-${self:custom.stage}.FormQuestionsTableArn}
  FormQuestionsTableStreamArn: ${cf:database-${self:custom.stage}.FormQuestionsTableStreamArn, cf:database-master.FormQuestionsTableStreamArn}
  FormsTableName: ${env:FORMS_TABLE_NAME, cf:database-${self:custom.stage}.FormsTableName}
  FormsTableArn: ${env:FORMS_TABLE_ARN, cf:database-${self:custom.stage}.FormsTableArn}
  FormsTableStreamArn: ${cf:database-${self:custom.stage}.FormsTableStreamArn, cf:database-master.FormsTableStreamArn}
  StateFormsTableName: ${env:STATE_FORMS_TABLE_NAME, cf:database-${self:custom.stage}.StateFormsTableName}
  StateFormsTableArn: ${env:STATE_FORMS_TABLE_ARN, cf:database-${self:custom.stage}.StateFormsTableArn}
  StateTableStreamArn: ${cf:database-${self:custom.stage}.StateTableStreamArn, cf:database-master.StateTableStreamArn}
  StatesTableName: ${env:STATES_TABLE_NAME, cf:database-${self:custom.stage}.StatesTableName}
  StatesTableArn: ${env:STATES_TABLE_ARN, cf:database-${self:custom.stage}.StatesTableArn}
  StatusTableName: ${env:STATUS_TABLE_NAME, cf:database-${self:custom.stage}.StatusTableName}
  StatusTableArn: ${env:STATUS_TABLE_ARN, cf:database-${self:custom.stage}.StatusTableArn}
  StatusTableStreamArn: ${cf:database-${self:custom.stage}.StatusTableStreamArn, cf:database-master.StatusTableStreamArn}
  AuthUserTableName: ${env:AUTH_USER_TABLE_NAME, cf:database-${self:custom.stage}.AuthUserTableName}
  AuthUserTableArn: ${env:AUTH_USER_TABLE_ARN, cf:database-${self:custom.stage}.AuthUserTableArn}
  AuthUserTableStreamArn: ${cf:database-${self:custom.stage}.AuthUserTableStreamArn, cf:database-master.AuthUserTableStreamArn}
  StateFormsTableStreamArn: ${cf:database-${self:custom.stage}.StateFormsTableStreamArn, cf:database-master.StateFormsTableStreamArn}
  bootstrapBrokerStringTls: ${ssm:/configuration/${self:custom.stage}/seds/bootstrapBrokerStringTls~true, ssm:/configuration/default/seds/bootstrapBrokerStringTls~true}
  vpcId: ${ssm:/configuration/${self:custom.stage}/vpc/id~true, ssm:/configuration/default/vpc/id~true}
  webAclName: ${self:service}-${self:custom.stage}-webacl
  associateWaf:
    name: ${self:custom.webAclName}
    version: V2
  dataSubnets:
    - ${ssm:/configuration/${self:custom.stage}/vpc/subnets/kubernetes/a/id~true, ssm:/configuration/default/vpc/subnets/kubernetes/a/id~true}
    - ${ssm:/configuration/${self:custom.stage}/vpc/subnets/kubernetes/b/id~true, ssm:/configuration/default/vpc/subnets/kubernetes/b/id~true}
    - ${ssm:/configuration/${self:custom.stage}/vpc/subnets/kubernetes/c/id~true, ssm:/configuration/default/vpc/subnets/kubernetes/c/id~true}
  privateSubnets:
    - ${ssm:/configuration/${self:custom.stage}/vpc/subnets/private/a/id~true, ssm:/configuration/default/vpc/subnets/private/a/id~true}
    - ${ssm:/configuration/${self:custom.stage}/vpc/subnets/private/b/id~true, ssm:/configuration/default/vpc/subnets/private/b/id~true}
    - ${ssm:/configuration/${self:custom.stage}/vpc/subnets/private/c/id~true, ssm:/configuration/default/vpc/subnets/private/c/id~true}
  warmupEnabled:
    production: true
    development: false
  warmup:
    enabled: ${self:custom.warmupEnabled.${self:custom.infrastructureType}}
    role: LambdaWarmupRole
    vpc: false
    events:
      - schedule: rate(4 minutes)
    timeout: 20
    prewarm: true
    concurrency: 5
    folderName: node_modules/serverless-bundle/src/_warmup
    cleanFolder: false
  scripts:
    hooks:
      package:setupProviderConfiguration: |
        # Remove the timestamp line from the warmup handler so a new function is uploaded
        #   only if a configuration has truly changed.
        set -e
        if [ -d "node_modules/serverless-bundle/src/_warmup" ]; then
          cd node_modules/serverless-bundle/src/_warmup
          sed '/Generated/d' index.js > index.js.sub && mv -f index.js.sub index.js
        fi

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment: # Service wide environment variables
    tbl_age_ranges: ${self:custom.AgeRangesTableName}
    tbl_form_answers: ${self:custom.FormAnswersTableName}
    tbl_form_questions: ${self:custom.FormQuestionsTableName}
    tbl_forms: ${self:custom.FormsTableName}
    tbl_state_forms: ${self:custom.StateFormsTableName}
    tbl_states: ${self:custom.StatesTableName}
    tbl_status: ${self:custom.StatusTableName}
    AgeRangesTableName: ${env:AGE_RANGES_TABLE_NAME, cf:database-${self:custom.stage}.AgeRangesTableName}
    AgeRangesTableArn: ${env:AGE_RANGES_TABLE_ARN, cf:database-${self:custom.stage}.AgeRangesTableArn}
    FormAnswersTableName: ${env:FORM_ANSWERS_TABLE_NAME, cf:database-${self:custom.stage}.FormAnswersTableName}
    FormAnswersTableArn: ${env:FORM_ANSWERS_TABLE_ARN, cf:database-${self:custom.stage}.FormAnswersTableArn}
    FormQuestionsTableName: ${env:FORM_QUESTIONS_TABLE_NAME, cf:database-${self:custom.stage}.FormQuestionsTableName}
    FormQuestionsTableArn: ${env:FORM_QUESTIONS_TABLE_ARN, cf:database-${self:custom.stage}.FormQuestionsTableArn}
    FormsTableName: ${env:FORMS_TABLE_NAME, cf:database-${self:custom.stage}.FormsTableName}
    FormsTableArn: ${env:FORMS_TABLE_ARN, cf:database-${self:custom.stage}.FormsTableArn}
    StateFormsTableName: ${env:STATE_FORMS_TABLE_NAME, cf:database-${self:custom.stage}.StateFormsTableName}
    StateFormsTableArn: ${env:STATE_FORMS_TABLE_ARN, cf:database-${self:custom.stage}.StateFormsTableArn}
    StatesTableName: ${env:STATES_TABLE_NAME, cf:database-${self:custom.stage}.StatesTableName}
    StatesTableArn: ${env:STATES_TABLE_ARN, cf:database-${self:custom.stage}.StatesTableArn}
    StatusTableName: ${env:STATUS_TABLE_NAME, cf:database-${self:custom.stage}.StatusTableName}
    StatusTableArn: ${env:STATUS_TABLE_ARN, cf:database-${self:custom.stage}.StatusTableArn}
    AuthUserTableName: ${env:AUTH_USER_TABLE_NAME, cf:database-${self:custom.stage}.AuthUserTableName}
    AuthUserTableArn: ${env:AUTH_USER_TABLE_ARN, cf:database-${self:custom.stage}.AuthUserTableArn}

functions:
  loadData:
    handler: handlers/load-data/post/uploadData.main
    role: LambdaApiRole
    events:
      - http:
          path: load-data/upload
          method: post
          cors: true
          authorizer: aws_iam
  postKafkaData:
    handler: handlers/kafka/post/postKafkaData.handler
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.FormAnswersTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.StateFormsTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.FormQuestionsTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.FormsTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.StateTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.StatusTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.AuthUserTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.AgeRangesTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
    role: LambdaApiRole
    environment:
      BOOTSTRAP_BROKER_STRING_TLS: ${self:custom.bootstrapBrokerStringTls}
    maximumRetryAttempts: 2
    vpc:
      securityGroupIds:
        - Ref: KafkaSecurityGroup
      subnetIds: ${self:custom.privateSubnets}
  getTableNames:
    handler: handlers/load-data/get/getTableNames.main
    role: LambdaApiRole
    events:
      - http:
          path: load-data/get-table-names
          method: get
          cors: true
          authorizer: aws_iam
  exportToExcel:
    handler: export/exportToExcel.main
    role: LambdaApiRole
    events:
      - http:
          path: export/export-to-excel
          method: post
          cors: true
          authorizer: aws_iam
  getUserById:
    handler: handlers/users/get/getUserById.main
    role: LambdaApiRole
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
          authorizer: aws_iam
  getUsers:
    handler: handlers/users/get/listUsers.main
    role: LambdaApiRole
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: aws_iam
  obtainUserByUsername:
    handler: handlers/users/post/obtainUserByUsername.main
    role: LambdaApiRole
    events:
      - http:
          path: users/get
          method: post
          cors: true
          authorizer: aws_iam
  obtainUsernameBySub:
    handler: handlers/users/post/obtainUsernameBySub.main
    role: LambdaApiRole
    events:
      - http:
          path: users/sub
          method: post
          cors: true
          authorizer: aws_iam
  obtainUserByEmail:
    handler: handlers/users/post/obtainUserByEmail.main
    role: LambdaApiRole
    events:
      - http:
          path: users/get/email
          method: post
          cors: true
          authorizer: aws_iam
  obtainUserStamp:
    handler: handlers/users/get/getUsername.main
    role: LambdaApiRole
    events:
      - http:
          path: users/get/username
          method: post
          cors: true
          authorizer: aws_iam
  createUser:
    handler: handlers/users/post/createUser.main
    role: LambdaApiRole
    events:
      - http:
          path: users/add
          method: post
          cors: true
          authorizer: aws_iam
  deleteUser:
    handler: handlers/users/post/deleteUser.main
    role: LambdaApiRole
    events:
      - http:
          path: users/delete
          method: post
          cors: true
          authorizer: aws_iam
  activateDeactivateUser:
    handler: handlers/users/post/activateDeactivateUser.main
    role: LambdaApiRole
    events:
      - http:
          path: users/activation/{username}
          method: post
          cors: true
          authorizer: aws_iam
  updateUser:
    handler: handlers/users/post/updateUser.main
    role: LambdaApiRole
    events:
      - http:
          path: users/update/{userId}
          method: post
          cors: true
          authorizer: aws_iam
  getForm:
    handler: handlers/forms/get.main
    role: LambdaApiRole
    events:
      - http:
          path: single-form/{state}/{specifiedYear}/{quarter}/{form}
          method: get
          cors: true
          authorizer: aws_iam
  getStateFormList:
    handler: handlers/forms/getFormsList.main
    role: LambdaApiRole
    events:
      - http:
          path: forms/{stateId}/{specifiedYear}/{quarter}
          method: get
          cors: true
          authorizer: aws_iam
  obtainAvailableForms:
    handler: handlers/forms/post/obtainAvailableForms.main
    role: LambdaApiRole
    events:
      - http:
          path: forms/obtainAvailableForms
          method: post
          cors: true
          authorizer: aws_iam
  getFormTypes:
    handler: handlers/forms/get/getFormTypes.main
    role: LambdaApiRole
    events:
      - http:
          path: form-types
          method: get
          cors: true
          authorizer: aws_iam
  getAgeRanges:
    handler: handlers/age-ranges/get/getAgeRanges.main
    role: LambdaApiRole
    events:
      - http:
          path: age-ranges
          method: get
          cors: true
          authorizer: aws_iam
  getStates:
    handler: handlers/states/get/getStates.main
    role: LambdaApiRole
    events:
      - http:
          path: states
          method: get
          cors: true
          authorizer: aws_iam
  getStatuses:
    handler: handlers/statuses/get/getStatuses.main
    role: LambdaApiRole
    events:
      - http:
          path: statuses
          method: get
          cors: true
          authorizer: aws_iam
  uncertified:
    handler: handlers/notification/uncertified.main
    role: LambdaApiRole
    events:
      - http:
          path: notification/uncertified
          method: post
          cors: true
          authorizer: aws_iam
  generateQuarterForms:
    handler: handlers/forms/post/generateQuarterForms.main
    role: LambdaApiRole
    events:
      - http:
          path: generate-forms
          method: post
          cors: true
          authorizer: aws_iam
      - schedule:
          enabled: false
          rate: cron(0 0 1 */3 ? *)
    timeout: 800
  stateUsersEmail:
    handler: handlers/notification/stateUsers.main
    role: LambdaApiRole
    events:
      - http:
          path: notification/stateUsersEmail
          method: post
          cors: true
          authorizer: aws_iam
      - schedule:
          enabled: false
          rate: cron(0 0 1 */3 ? *)
  businessUsersEmail:
    handler: handlers/notification/businessUsers.main
    role: LambdaApiRole
    events:
      - http:
          path: notification/businessUsersEmail
          method: post
          cors: true
          authorizer: aws_iam
      - schedule:
          enabled: false
          rate: cron(0 0 1 */3 ? *)
  saveForm:
    handler: handlers/forms/post/saveForm.main
    role: LambdaApiRole
    events:
      - http:
          path: single-form/save
          method: post
          cors: true
          authorizer: aws_iam

resources:
  - ${file(resources/base.yml)}

  # Roles
  - ${file(resources/roles.yml)}

  # API Gateway
  - ${file(resources/api-gateway.yml)}