service: ui-waf-log-assoc

plugins:
  - serverless-plugin-scripts
  - serverless-stack-termination-protection

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}

custom:
  project: "seds"
  stage: ${opt:stage, self:provider.stage}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
      - develop
      - main
      - impl
      - val
      - prod
  wafAclArn: ${param:CloudFrontWebAclArn}
  firehoseStreamArn: ${param:FirehoseArn}
  scripts:
    hooks:
      # Associate the Firehose and the WAF Acl
      deploy:finalize: |
        aws wafv2 put-logging-configuration \
          --logging-configuration ResourceArn=${self:custom.wafAclArn},LogDestinationConfigs=${self:custom.firehoseStreamArn} \
          --region ${self:provider.region}

resources:
  Resources:
    Honk: # this is just because it won't deploy unless we have some resource being created
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Value: "honk"
