import handler from "../../../libs/handler-lib.ts";
import dynamoDb from "../../../libs/dynamodb-lib.ts";
import { getUserDetailsFromEvent } from "../../../libs/authorization.ts";
import { createUser } from "../post/createUser.ts";
import { AuthUser } from "../../../storage/users.ts";
import { ok } from "../../../libs/response-lib.ts";

/**
 * Get **or** create the AuthUser record matching this request's auth token.
 */
export const main = handler(async (event, context) => {
  const userDetails = await getUserDetailsFromEvent(event);
  const usernameSub = userDetails.usernameSub;
  if (!usernameSub) {
    throw new Error(`User token must contain a 'sub' property!`);
  }

  let authUser = await scanForUserWithSub(usernameSub);
  if (!authUser) {
    await createUser(userDetails);
    authUser = await scanForUserWithSub(usernameSub);
    if (!authUser) {
      throw new Error(`Failed to create new AuthUser record!`);
    }
  } else {
    await recordLogin(authUser, userDetails);
  }

  return ok(authUser);
});

/**
 * Scan the AuthUser table for the user with the given `usernameSub`.
 *
 * Since the table is keyed by UserId, this sadly must be a full-table scan.
 * But the table is small (~300 users after 5 years), so the scan is cheap.
 * @param usernameSub - The `sub` UUID generated by Cognito
 */
export const scanForUserWithSub = async (usernameSub: string) => {
  const scanResult = await dynamoDb.scan({
    TableName: process.env.AuthUserTable,
    FilterExpression: "usernameSub = :usernameSub",
    ExpressionAttributeValues: { ":usernameSub": usernameSub },
  });

  return scanResult.Items?.[0] as AuthUser | undefined;
};

/**
 * Record the fact that this user has logged in.
 * Also, ensure the AuthUser record stays up-to-date with Cognito.
 *
 * This endpoint will probably be called multiple times per user session,
 * so we're not recording "the moment of login" so much as "user activity".
 * The date usually matters more than the exact time,
 * so this is still valuable information.
 */
const recordLogin = async (authUser: any, userDetails: any) => {
  await dynamoDb.update({
    TableName: process.env.AuthUserTable,
    Key: { userId: authUser.userId },
    UpdateExpression:
      "SET firstName = :firstName, lastName = :lastName, email = :email, lastLogin = :lastLogin",
    ExpressionAttributeValues: {
      ":firstName": userDetails.firstName,
      ":lastName": userDetails.lastName,
      ":email": userDetails.email,
      ":lastLogin": new Date().toISOString(),
    },
  });
};
