repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.272
    hooks:
      - id: ruff
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: branch-name-validation
        name: branch-name-validation
        entry: .github/branchNameValidation.sh
        language: script
        pass_filenames: false
      - id: validate-commit-msg
        name: validate-commit-msg
        entry: .github/validateCommitMessage.sh
        language: script
        stages: [commit-msg]
