#!/bin/bash

set -eu -o pipefail

# this is the entrypoint for development. It wraps up compiling and calling run.ts
# all arguments, changes, etc. should be found in cli/run.ts

# this script checks for all the prereqs and then calls run.ts

export REGION_A=us-east-1
export PROJECT=seds

# check node exists
if ! which node > /dev/null ; then
	echo "node not found on the system. Install version in .nvmrc based on instructions in README"
	exit 1
fi

# check node version
if ! diff  <(cat .nvmrc | tr -d '\n') <(node -v | tr -d '\n') > /dev/null ; then
	echo "node version does not match the version required in .nvmrc"
	echo "If using nvm, run 'nvm use'"
	exit 1
fi

# check yarn exists
if ! which yarn > /dev/null ; then
	echo "yarn not found on the system. On macOS, you can install it with 'brew install yarn'"
	exit 1
fi


# Parse arguments
UPDATE_ENV=false
LOCAL=false
ARGS=()

for arg in "$@"; do
    case $arg in
        update-env)
        UPDATE_ENV=true
        ;;
        local)
        LOCAL=true
        ;;
    esac
    ARGS+=("$arg")
done

if [ "$UPDATE_ENV" = true ]; then
    if ! which op > /dev/null; then
        echo "The MDCT team uses 1Password to store and retrieve development credentials. On macOS, you can install it with 'brew install --cask 1password-cli'"
        exit 1
    fi
fi

if [ "$LOCAL" = true ]; then
    if ! which docker > /dev/null ; then
        echo "docker not found on the system. On macOS, you can install it with 'brew install docker'"
        exit 1
    fi

    if ! which colima > /dev/null ; then
        echo "colima not found on the system. On macOS, you can install it with 'brew install colima'"
        exit 1
    fi

    if ! which localstack > /dev/null ; then
        echo "localstack not found on the system. On macOS, you can install it with 'brew install localstack/tap/localstack-cli'"
        exit 1
    fi

    if ! colima status 2>&1 | grep -q "colima is running" ; then
        echo "colima installed but not running. We'll start it up for you now."
        colima start --cpu 4 --memory 10
    fi

    if ! localstack status | grep -q "running" ; then
        echo "localstack is installed but not running. We'll start it up for you now."
        localstack start > /dev/null 2>&1 &
    fi
fi

pushd cli
yarn install --frozen-lockfile
popd 

# run the CLI
./cli/node_modules/.bin/tsx cli/run.ts "${ARGS[@]-}"
