services:
  # wave 1: no dependencies
  database:
    path: services/database
  stream-functions:
    path: services/stream-functions
  ui-waflog-s3-bucket:
    path: services/ui-waflog-s3-bucket

  # depends on ui-waflog-s3-bucket
  ui:
    path: services/ui
    params:
      WaflogsUploadBucketArn: ${ui-waflog-s3-bucket.WaflogsUploadBucketArn}

  # depends on ui
  ui-waf-log-assoc:
    path: services/ui-waf-log-assoc
    params:
      CloudFrontWebAclArn: ${ui.CloudFrontWebAclArn}
      FirehoseArn: ${ui.FirehoseArn}

  # depends on database
  app-api:
    path: services/app-api
    params:
      AgeRangesTableName: ${database.AgeRangesTableName}
      AgeRangesTableArn: ${database.AgeRangesTableArn}
      AgeRangesTableStreamArn: ${database.AgeRangesTableStreamArn}
      FormAnswersTableName: ${database.FormAnswersTableName}
      FormAnswersTableArn: ${database.FormAnswersTableArn}
      FormAnswersTableStreamArn: ${database.FormAnswersTableStreamArn}
      FormQuestionsTableName: ${database.FormQuestionsTableName}
      FormQuestionsTableArn: ${database.FormQuestionsTableArn}
      FormQuestionsTableStreamArn: ${database.FormQuestionsTableStreamArn}
      FormsTableName: ${database.FormsTableName}
      FormsTableArn: ${database.FormsTableArn}
      FormsTableStreamArn: ${database.FormsTableStreamArn}
      FormTemplatesTableName: ${database.FormTemplatesTableName}
      FormTemplatesTableArn: ${database.FormTemplatesTableArn}
      FormTemplatesTableStreamArn: ${database.FormTemplatesTableStreamArn}
      StateFormsTableName: ${database.StateFormsTableName}
      StateFormsTableArn: ${database.StateFormsTableArn}
      StateTableStreamArn: ${database.StateTableStreamArn}
      StatesTableName: ${database.StatesTableName}
      StatesTableArn: ${database.StatesTableArn}
      StatusTableName: ${database.StatusTableName}
      StatusTableArn: ${database.StatusTableArn}
      StatusTableStreamArn: ${database.StatusTableStreamArn}
      AuthUserTableName: ${database.AuthUserTableName}
      AuthUserTableArn: ${database.AuthUserTableArn}
      AuthUserTableStreamArn: ${database.AuthUserTableStreamArn}
      AuthUserRolesTableName: ${database.AuthUserRolesTableName}
      AuthUserRolesTableArn: ${database.AuthUserRolesTableArn}
      AuthUserStatesTableName: ${database.AuthUserStatesTableName}
      AuthUserStatesTableArn: ${database.AuthUserStatesTableArn}
      AuthUserStatesTableStreamArn: ${database.AuthUserStatesTableStreamArn}
      StateFormsTableStreamArn: ${database.StateFormsTableStreamArn}
      AuthUserRolesTableStreamArn: ${database.AuthUserRolesTableStreamArn}

  # depends on app-api and ui
  ui-auth:
    path: services/ui-auth
    params:
      ApiGatewayRestApiName: ${app-api.ApiGatewayRestApiName}
      ApplicationEndpointUrl: ${ui.ApplicationEndpointUrl}

  # depends on app-api, ui, and ui-auth
  ui-src:
    path: services/ui-src
    params:
      ApiRegion: ${app-api.Region}
      ApiGatewayRestApiUrl: ${app-api.ApiGatewayRestApiUrl}
      CognitoRegion: ${ui-auth.Region}
      IdentityPoolId: ${ui-auth.IdentityPoolId}
      UserPoolId: ${ui-auth.UserPoolId}
      UserPoolClientId: ${ui-auth.UserPoolClientId}
      UserPoolClientDomain: ${ui-auth.UserPoolClientDomain}
      CloudFrontDistributionId: ${ui.CloudFrontDistributionId}
      ApplicationEndpointUrl: ${ui.ApplicationEndpointUrl}