const seed = {
  name: "Form Answers - Test Data",
  filenames: [
    [
      "../../../../../src/database/initial_data_load/form_answers_AL.json",
      "../../../../../src/database/initial_data_load/form_answers_AK.json",
      "../../../../../src/database/initial_data_load/form_answers_AZ.json",
      "../../../../../src/database/initial_data_load/form_answers_AR.json",
      "../../../../../src/database/initial_data_load/form_answers_CA.json",
      "../../../../../src/database/initial_data_load/form_answers_CO.json",
      "../../../../../src/database/initial_data_load/form_answers_CT.json",
      "../../../../../src/database/initial_data_load/form_answers_DE.json",
      "../../../../../src/database/initial_data_load/form_answers_DC.json",
      "../../../../../src/database/initial_data_load/form_answers_FL.json",
      "../../../../../src/database/initial_data_load/form_answers_GA.json",
      "../../../../../src/database/initial_data_load/form_answers_HI.json",
      "../../../../../src/database/initial_data_load/form_answers_ID.json",
      "../../../../../src/database/initial_data_load/form_answers_IL.json",
      "../../../../../src/database/initial_data_load/form_answers_IN.json",
      "../../../../../src/database/initial_data_load/form_answers_IA.json",
      "../../../../../src/database/initial_data_load/form_answers_KS.json",
      "../../../../../src/database/initial_data_load/form_answers_KY.json",
      "../../../../../src/database/initial_data_load/form_answers_LA.json",
      "../../../../../src/database/initial_data_load/form_answers_ME.json",
      "../../../../../src/database/initial_data_load/form_answers_MD.json",
      "../../../../../src/database/initial_data_load/form_answers_MA.json",
      "../../../../../src/database/initial_data_load/form_answers_MI.json",
      "../../../../../src/database/initial_data_load/form_answers_MN.json",
      "../../../../../src/database/initial_data_load/form_answers_MO.json",
      "../../../../../src/database/initial_data_load/form_answers_MS.json",
      "../../../../../src/database/initial_data_load/form_answers_MT.json",
      "../../../../../src/database/initial_data_load/form_answers_NE.json",
      "../../../../../src/database/initial_data_load/form_answers_NV.json",
      "../../../../../src/database/initial_data_load/form_answers_NH.json",
      "../../../../../src/database/initial_data_load/form_answers_NJ.json",
      "../../../../../src/database/initial_data_load/form_answers_NM.json",
      "../../../../../src/database/initial_data_load/form_answers_NY.json",
      "../../../../../src/database/initial_data_load/form_answers_NC.json",
      "../../../../../src/database/initial_data_load/form_answers_ND.json",
      "../../../../../src/database/initial_data_load/form_answers_OH.json",
      "../../../../../src/database/initial_data_load/form_answers_OK.json",
      "../../../../../src/database/initial_data_load/form_answers_OR.json",
      "../../../../../src/database/initial_data_load/form_answers_PA.json",
      "../../../../../src/database/initial_data_load/form_answers_RI.json",
      "../../../../../src/database/initial_data_load/form_answers_SC.json",
      "../../../../../src/database/initial_data_load/form_answers_SD.json",
      "../../../../../src/database/initial_data_load/form_answers_TN.json",
      "../../../../../src/database/initial_data_load/form_answers_TX.json",
      "../../../../../src/database/initial_data_load/form_answers_UT.json",
      "../../../../../src/database/initial_data_load/form_answers_VT.json",
      "../../../../../src/database/initial_data_load/form_answers_VA.json",
      "../../../../../src/database/initial_data_load/form_answers_WA.json",
      "../../../../../src/database/initial_data_load/form_answers_WV.json",
      "../../../../../src/database/initial_data_load/form_answers_WI.json",
      "../../../../../src/database/initial_data_load/form_answers_WY.json",
      "../../../../../src/database/initial_data_load/form_answers_AL_2021Q1.json",
      "../../../../../src/database/initial_data_load/form_answers_MD_2021Q1.json",
      "../../../../../src/database/initial_data_load/form_answers_PA_2021Q1.json",
      "../../../../../src/database/initial_data_load/form_answers_AL_2020.json",
      "../../../../../src/database/initial_data_load/form_answers_MD_2020.json",
      "../../../../../src/database/initial_data_load/form_answers_PA_2020.json",
    ],
  ],
  tableNameBuilder: (stage) => `${stage}-form-answers`,
  keys: ["answer_entry", "state_form"],
};

module.exports = seed;
