module.exports = {
  tables: [
    {
      filenames: ["data/initial_data_load/auth_user.json"],
      tableNameSuffix: "auth-user",
    },
    {
      filenames: [
        "data/initial_data_load/form_questions_2021.json",
        "data/initial_data_load/form_questions_2020.json",
      ],
      tableNameSuffix: "form-questions",
    },
    {
      filenames: [
        "data/initial_data_load/form_template_2019.json",
        "data/initial_data_load/form_template_2020.json",
        "data/initial_data_load/form_template_2021.json",
      ],
      tableNameSuffix: "form-templates",
    },
    {
      filenames: ["data/initial_data_load/forms.json"],
      tableNameSuffix: "forms",
    },
    {
      filenames: [
        "data/initial_data_load/form_answers_AL.json",
        "data/initial_data_load/form_answers_AK.json",
        "data/initial_data_load/form_answers_AZ.json",
        "data/initial_data_load/form_answers_AR.json",
        "data/initial_data_load/form_answers_CA.json",
        "data/initial_data_load/form_answers_CO.json",
        "data/initial_data_load/form_answers_CT.json",
        "data/initial_data_load/form_answers_DE.json",
        "data/initial_data_load/form_answers_DC.json",
        "data/initial_data_load/form_answers_FL.json",
        "data/initial_data_load/form_answers_GA.json",
        "data/initial_data_load/form_answers_HI.json",
        "data/initial_data_load/form_answers_ID.json",
        "data/initial_data_load/form_answers_IL.json",
        "data/initial_data_load/form_answers_IN.json",
        "data/initial_data_load/form_answers_IA.json",
        "data/initial_data_load/form_answers_KS.json",
        "data/initial_data_load/form_answers_KY.json",
        "data/initial_data_load/form_answers_LA.json",
        "data/initial_data_load/form_answers_ME.json",
        "data/initial_data_load/form_answers_MD.json",
        "data/initial_data_load/form_answers_MA.json",
        "data/initial_data_load/form_answers_MI.json",
        "data/initial_data_load/form_answers_MN.json",
        "data/initial_data_load/form_answers_MO.json",
        "data/initial_data_load/form_answers_MS.json",
        "data/initial_data_load/form_answers_MT.json",
        "data/initial_data_load/form_answers_NE.json",
        "data/initial_data_load/form_answers_NV.json",
        "data/initial_data_load/form_answers_NH.json",
        "data/initial_data_load/form_answers_NJ.json",
        "data/initial_data_load/form_answers_NM.json",
        "data/initial_data_load/form_answers_NY.json",
        "data/initial_data_load/form_answers_NC.json",
        "data/initial_data_load/form_answers_ND.json",
        "data/initial_data_load/form_answers_OH.json",
        "data/initial_data_load/form_answers_OK.json",
        "data/initial_data_load/form_answers_OR.json",
        "data/initial_data_load/form_answers_PA.json",
        "data/initial_data_load/form_answers_RI.json",
        "data/initial_data_load/form_answers_SC.json",
        "data/initial_data_load/form_answers_SD.json",
        "data/initial_data_load/form_answers_TN.json",
        "data/initial_data_load/form_answers_TX.json",
        "data/initial_data_load/form_answers_UT.json",
        "data/initial_data_load/form_answers_VT.json",
        "data/initial_data_load/form_answers_VA.json",
        "data/initial_data_load/form_answers_WA.json",
        "data/initial_data_load/form_answers_WV.json",
        "data/initial_data_load/form_answers_WI.json",
        "data/initial_data_load/form_answers_WY.json",
        "data/initial_data_load/form_answers_AL_2021Q1.json",
        "data/initial_data_load/form_answers_MD_2021Q1.json",
        "data/initial_data_load/form_answers_PA_2021Q1.json",
        "data/initial_data_load/form_answers_AL_2020.json",
        "data/initial_data_load/form_answers_MD_2020.json",
        "data/initial_data_load/form_answers_PA_2020.json",
      ],
      tableNameSuffix: "form-answers",
    },
    {
      filenames: [
        "data/initial_data_load/state_forms.json",
        "data/initial_data_load/state_forms_2021Q1.json",
        "data/initial_data_load/state_forms_2020.json",
      ],
      tableNameSuffix: "state-forms",
    },
    {
      filenames: ["data/initial_data_load/states.json"],
      tableNameSuffix: "states",
    },
  ],
};
