service: stream-functions

frameworkVersion: "4"

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-stack-termination-protection

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}

custom:
  project: "seds"
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages: # This is a list of common names for important envs that should not be destroyed.  You can remove the stage names your project doesn't use; this list is meant to be inclusive.
      - master
      - val
      - production
      - develop
      - main
      - impl
      - val
      - prod
resources:
  Resources:
    Honk: # this is just because it won't deploy unless we have some resource being created
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Value: "honk"
