service: ui-waflog-s3-bucket

frameworkVersion: "4"

plugins:
  - serverless-stack-termination-protection

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}

custom:
  project: "seds"
  stage: ${opt:stage, self:provider.stage}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
      - develop
      - main
      - impl
      - val
      - prod

resources:
  Resources:
    WaflogsUploadBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: !Sub ${AWS::AccountId}-${self:custom.stage}-waflogs
        BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        VersioningConfiguration:
          Status: Enabled

    WaflogsUploadBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "AllowSSLRequestsOnly"
              Effect: Deny
              Action: "s3:*"
              Principal: "*"
              Resource:
                - !Sub arn:aws:s3:::${WaflogsUploadBucket}/*
                - !Sub arn:aws:s3:::${WaflogsUploadBucket}
              Condition:
                Bool:
                  aws:SecureTransport: false
        Bucket: !Ref WaflogsUploadBucket

  Outputs:
    WaflogsUploadBucketArn:
      Value: !GetAtt WaflogsUploadBucket.Arn
