import dynamoDb from "../libs/dynamodb-lib.ts";

/** The shape of an object in the `auth-user` table */
export type AuthUser = {
  /**
   * A unique numeric string generated with createUser.ts
   * @example "42"
   */
  userId: string;
  /** A UUID generated by Cognito */
  usernameSub: string;
  /**
   * Often a 4-character EUA ID. Sometimes an email address.
   */
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  role: "state" | "business" | "admin";
  /**
   * For state users, the 2-letter postal abbreviation of their US state.
   *
   * For admin and business users, this property will be absent;
   * Admin and business users can view data from any state.
   *
   * This will also be absent for a state user who has never selected a state.
   * For that to happen they must have logged in to SEDS
   * (in order to create an AuthUser record in the first place),
   * but not proceeded past the landing page
   * (which would have asked them to select their state).
   *
   * In theory, an admin user has permissions to remove a state user's state.
   *
   * In past versions of SEDS, admins could create AuthUser records directly;
   * this may also have resulted in some old records with no state.
   */
  state?: string;
};

export const putUser = async (user: AuthUser) => {
  await dynamoDb.put({
    TableName: process.env.AuthUserTable,
    Item: user,
  });
};

export const scanUsersByRole = async (role: string) => {
  const response = await dynamoDb.scan({
    TableName: process.env.AuthUserTable,
    FilterExpression: "#role = :role",
    ExpressionAttributeNames: { "#role": "role" },
    ExpressionAttributeValues: { ":role": role },
  });
  return response.Items as AuthUser[];
};

export const scanForUserByUsername = async (username: string) => {
  const response = await dynamoDb.scan({
    TableName: process.env.AuthUserTable,
    FilterExpression: "username = :username",
    ExpressionAttributeValues: { ":username": username },
  });
  return response.Items?.[0] as AuthUser | undefined;
};
