import dynamoDb from "../libs/dynamodb-lib.ts";
import { DateString } from "../shared/types.ts";

/** The shape of an object in the `auth-user` table */
export type AuthUser = {
  /**
   * A unique numeric string generated with createUser.ts
   * @example "42"
   */
  userId: string;
  /** A UUID generated by Cognito */
  usernameSub: string;
  /**
   * Often a 4-character EUA ID. Sometimes an email address.
   */
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  role: "state" | "business" | "admin";
  /**
   * For state users, the 2-letter postal abbreviation of their US state.
   *
   * For admin and business users, this property will be absent;
   * Admin and business users can view data from any state.
   *
   * This will also be absent for a state user who has never selected a state.
   * For that to happen they must have logged in to SEDS
   * (in order to create an AuthUser record in the first place),
   * but not proceeded past the landing page
   * (which would have asked them to select their state).
   *
   * In theory, an admin user has permissions to remove a state user's state.
   *
   * In past versions of SEDS, admins could create AuthUser records directly;
   * this may also have resulted in some old records with no state.
   */
  state?: string;
  dateJoined: DateString;
  lastLogin: DateString;
};

const TableName = process.env.AuthUserTable;

export const putUser = async (user: AuthUser) => {
  await dynamoDb.put({
    TableName,
    Item: user,
  });
};

export const scanAllUsers = async () => {
  const response = await dynamoDb.scan({ TableName });
  return response.Items ?? ([] as AuthUser[]);
};

export const scanUsersByRole = async (role: string) => {
  const response = await dynamoDb.scan({
    TableName,
    FilterExpression: "#role = :role",
    ExpressionAttributeNames: { "#role": "role" },
    ExpressionAttributeValues: { ":role": role },
  });
  return response.Items as AuthUser[];
};

export const scanForUserByUsername = async (username: string) => {
  const response = await dynamoDb.scan({
    TableName,
    FilterExpression: "username = :username",
    ExpressionAttributeValues: { ":username": username },
  });
  return response.Items?.[0] as AuthUser | undefined;
};

/**
 * Scan the AuthUser table for the user with the given `usernameSub`.
 *
 * Since the table is keyed by UserId, this sadly must be a full-table scan.
 * But the table is small (~300 users after 5 years), so the scan is cheap.
 * @param usernameSub - The `sub` UUID generated by Cognito
 */
export const scanForUserWithSub = async (usernameSub: string) => {
  const scanResult = await dynamoDb.scan({
    TableName,
    FilterExpression: "usernameSub = :usernameSub",
    ExpressionAttributeValues: { ":usernameSub": usernameSub },
  });

  return scanResult.Items?.[0] as AuthUser | undefined;
};

export const getUser = async (userId: string) => {
  const result = await dynamoDb.get({
    TableName,
    Key: { userId },
  });
  return result.Item as AuthUser | undefined;
};

/**
 * Record the fact that this user has logged in.
 * Also, ensure the AuthUser record stays up-to-date with Cognito.
 *
 * This endpoint will probably be called multiple times per user session,
 * so we're not recording "the moment of login" so much as "user activity".
 * The date usually matters more than the exact time,
 * so this is still valuable information.
 */
export const recordLogin = async (
  userData: Pick<AuthUser, "userId" | "firstName" | "lastName" | "email">,
  lastLogin: DateString
) => {
  await dynamoDb.update({
    TableName,
    Key: { userId: userData.userId },
    UpdateExpression:
      "SET firstName = :firstName, lastName = :lastName, email = :email, lastLogin = :lastLogin",
    ExpressionAttributeValues: {
      ":firstName": userData.firstName,
      ":lastName": userData.lastName,
      ":email": userData.email,
      ":lastLogin": lastLogin,
    },
  });
};
