import dynamoDb from "../libs/dynamodb-lib.ts";

/** The shape of an object in the `auth-user` table */
export type AuthUser = {
  /**
   * A unique numeric string generated with createUser.ts
   * @example "42"
   */
  userId: string;
  /** A UUID generated by Cognito */
  usernameSub: string;
  email: string;
  /**
   * Often a 4-character EUA ID. Sometimes an email address.
   */
  username: string;
  role: "state" | "business" | "admin";
  states: string[] | string | null;
};

export const scanUsersByRole = async (role: string) => {
  const response = await dynamoDb.scan({
    TableName: process.env.AuthUserTable,
    FilterExpression: "#role = :role",
    ExpressionAttributeNames: { "#role": "role" },
    ExpressionAttributeValues: { ":role": role },
  });
  return response.Items as AuthUser[];
};
