name: Update Code.json
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
    # - cron: "0 0 1 * *" # monthly on day 1

permissions:
  contents: write
  pull-requests: write

jobs:
  update-code-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "20"

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: "1.22"

      - name: Install SCC
        run: go install github.com/boyter/scc/v3@v3.5.0

      - name: Update code.json
        id: update
        uses: DSACMS/automated-codejson-generator@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "master"

      - name: Approve and enable auto-merge PR
        run: |
          echo "${{github.actor}}"
          PR_URL=$(gh pr list --state open --json url,headRefName \
            --jq '.[] | select(.headRefName | startswith("code-json-")) | .url' \
            | head -n 1)

          echo "Found PR: $PR_URL"

          # Approve and auto-merge
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{secrets.GLOBAL_GH_PAT}}
